title: Hi, we're in love
description: > # this means to ignore newlines until "baseurl:"
  Hiiiiii. We're Ash & Yella and we're going on a world tour in 2024. We want this blog to be a space for family & friends to follow along.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ash & Yella # add your name
author-img: ashyells_airplane.jpg # add your photo
about-author: Hiiiiii. We're Ash & Yella and we're going on a world tour in 2024. We want this blog to be a space for family & friends to follow along. # add description
social-instagram: hiwereinlove # add your Facebook handle
social-email: hiwereinlove22@gmail.com # add your Email address

# Disqus
discus-identifier: hiwereinlove # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
